/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#333539",
        "surface": "#111317",
        "secondary-container": "#444955",
        "secondary-fixed-dim": "#c2c6d5",
        "background": "#0f1115",
        "tertiary-fixed-dim": "#c3c6d1",
        "on-primary-fixed": "#170065",
        "inverse-primary": "#5a48cc",
        "primary-fixed": "#e4dfff",
        "status-success": "#4ade80",
        "tertiary-container": "#8d909b",
        "surface-dim": "#111317",
        "tertiary-fixed": "#dfe2ee",
        "on-tertiary-container": "#262a32",
        "on-tertiary-fixed-variant": "#434750",
        "outline-variant": "#474554",
        "status-warning": "#e5b567",
        "surface-tint": "#c7bfff",
        "surface-container-low": "#1a1c20",
        "on-background": "#e2e2e8",
        "surface-container": "#1e2024",
        "surface-container-highest": "#333539",
        "on-tertiary-fixed": "#181c24",
        "inverse-on-surface": "#2f3035",
        "text-primary": "#e7e9f0",
        "outline": "#928e9f",
        "on-secondary-container": "#b4b8c7",
        "secondary": "#c2c6d5",
        "on-primary-fixed-variant": "#422cb3",
        "border": "#2a3142",
        "accent": "#7c6cf0",
        "accent-hover": "#9182f6",
        "surface-container-lowest": "#0c0e12",
        "error-container": "#93000a",
        "primary": "#7c6cf0",
        "primary-container": "#8e7fff",
        "on-primary": "#ffffff",
        "surface-bright": "#37393e",
        "inverse-surface": "#e2e2e8",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#171c26",
        "text-muted": "#8a92a8",
        "on-secondary-fixed-variant": "#424753",
        "status-error": "#e06c75",
        "on-surface": "#e2e2e8",
        "card": "#1b202b",
        "card-hover": "#232a3b",
        "card-selected": "#252c41",
        "error": "#ffb4ab",
        "tertiary": "#c3c6d1",
        "on-secondary": "#2b303c",
        "text-faint": "#5a6275",
        "on-primary-container": "#24008c",
        "primary-fixed-dim": "#c7bfff",
        "on-tertiary": "#2c3039",
        "on-surface-variant": "#c9c4d6",
        "secondary-fixed": "#dee2f1",
        "surface-container-high": "#282a2e",
        "accent-soft": "#2a2f52",
        "on-error": "#690005"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        lg: "24px",
        xl: "32px",
        "card-width": "178px",
        base: "4px",
        "card-height": "218px",
        sm: "8px",
        xs: "4px",
        gutter: "16px",
        md: "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["16px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
        "caption": ["9px", { lineHeight: "12px", fontWeight: "400" }]
      }
    }
  },
  plugins: []
};
