// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {services} from '../models';

export function BackupSave(arg1:string,arg2:string):Promise<string>;

export function CheckUpdate():Promise<core.UpdateResult>;

export function ClearEventHistory():Promise<void>;

export function DecryptGameAssets(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DetectGameEngine(arg1:string):Promise<Record<string, any>>;

export function ExecuteSync(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetConfig():Promise<core.AppConfig>;

export function GetData(arg1:string,arg2:string):Promise<core.DataResult>;

export function GetDataDir():Promise<string>;

export function GetEventHistory(arg1:number):Promise<Array<services.EventData>>;

export function GetGames():Promise<core.ScanResult>;

export function GetGamesDir():Promise<string>;

export function GetPlugins(arg1:string):Promise<Record<string, any>>;

export function GetSaveContent(arg1:string,arg2:string):Promise<core.SaveInfo>;

export function GetSaves(arg1:string):Promise<Record<string, any>>;

export function GetStatus():Promise<Record<string, any>>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function HasEncryptedAssets(arg1:string):Promise<boolean>;

export function LaunchGame(arg1:string,arg2:string,arg3:string):Promise<core.LaunchResult>;

export function OpenTarget(arg1:string):Promise<boolean>;

export function Ping():Promise<string>;

export function ReadEncryptionKey(arg1:string):Promise<any>;

export function RescanGames():Promise<core.ScanResult>;

export function ResetConfig():Promise<Record<string, any>>;

export function RestorePlugins(arg1:string):Promise<Record<string, any>>;

export function SetupMods(arg1:string):Promise<core.ModsResult>;

export function StopGame():Promise<Record<string, any>>;

export function ToggleFavorite(arg1:string):Promise<Record<string, any>>;

export function TogglePlugins(arg1:string,arg2:Array<string>,arg3:boolean,arg4:boolean):Promise<Record<string, any>>;

export function UpdateConfig(arg1:core.AppConfig):Promise<Record<string, any>>;

export function UpdateSaveContent(arg1:string,arg2:string,arg3:Record<string, any>):Promise<boolean>;
