// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupSave(arg1, arg2) {
  return window['go']['main']['App']['BackupSave'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearEventHistory() {
  return window['go']['main']['App']['ClearEventHistory']();
}

export function DecryptGameAssets(arg1, arg2) {
  return window['go']['main']['App']['DecryptGameAssets'](arg1, arg2);
}

export function DetectGameEngine(arg1) {
  return window['go']['main']['App']['DetectGameEngine'](arg1);
}

export function ExecuteSync(arg1, arg2) {
  return window['go']['main']['App']['ExecuteSync'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetData(arg1, arg2) {
  return window['go']['main']['App']['GetData'](arg1, arg2);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetEventHistory(arg1) {
  return window['go']['main']['App']['GetEventHistory'](arg1);
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetGamesDir() {
  return window['go']['main']['App']['GetGamesDir']();
}

export function GetPlugins(arg1) {
  return window['go']['main']['App']['GetPlugins'](arg1);
}

export function GetSaveContent(arg1, arg2) {
  return window['go']['main']['App']['GetSaveContent'](arg1, arg2);
}

export function GetSaves(arg1) {
  return window['go']['main']['App']['GetSaves'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function HasEncryptedAssets(arg1) {
  return window['go']['main']['App']['HasEncryptedAssets'](arg1);
}

export function LaunchGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['LaunchGame'](arg1, arg2, arg3);
}

export function OpenTarget(arg1) {
  return window['go']['main']['App']['OpenTarget'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function ReadEncryptionKey(arg1) {
  return window['go']['main']['App']['ReadEncryptionKey'](arg1);
}

export function RescanGames() {
  return window['go']['main']['App']['RescanGames']();
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function RestorePlugins(arg1) {
  return window['go']['main']['App']['RestorePlugins'](arg1);
}

export function SetupMods(arg1) {
  return window['go']['main']['App']['SetupMods'](arg1);
}

export function StopGame() {
  return window['go']['main']['App']['StopGame']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function TogglePlugins(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TogglePlugins'](arg1, arg2, arg3, arg4);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateSaveContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSaveContent'](arg1, arg2, arg3);
}
